spring:
    profiles:
      active: @profiles_active@
server:
    port: 8980
    ssl: 
        keyAlias: tomcat
        keyPassword: 123456
        keyStoryType: RSA
        keyStore: classpath:.keystore