spring:
    profiles:
        active: @profiles_active@
    mvc:
       view: 
          prefix: /WEB-INF/pages/
          suffix: .jsp
server:
    port: 8980
    ssl: 
        keyAlias: tomcat
        keyPassword: 123456
        keyStoryType: RSA
        keyStore: classpath:.keystore